name: call-build

on:
  workflow_dispatch: 
#  push:
#    branches: 
#      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: github-actions-practice
      environment: staging
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  show-version:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Show build version
        run: |
          echo "Build version: ${{ needs.build.outputs.build_version }}"
