name: call-build

on:
  push:
    branches: 
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

  show-version:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Show build version
        run: |
          echo "Build version: ${{ needs.build.outputs.build_version }}"
