name: hello workflow

on: 
  push:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codr
        run: actions/checkout@4

      - name: greet
        run: 'echo "Hello from GitHub Actions!"'
        
