name: matrix

on:
  workflow_dispsche:

jobs:
  test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version:
           - '3.12'
           - '3.13'
           - '3.14'
     
     steps:
       - name: checkeout code
         uses: actions\checkout@v4
          
       - name: python setup
         uses: actions\setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
            
       - name: python verrsion
         run: python --version
    
  
