name: pr-check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps: 
      - name: show pr branch
        run: echo "PR check running for branch ${{ github.head_ref }}"
      #testing full request workflow
