name: Reusable Build

on:
  workflow_call:
    inputs:
      app_name:
        description: "Application name"
        required: true
        type: string
     
      environment:
        description: "Deployment environment"
        required: true
        type: string
        default: staging
    
    secrets:
      docker_token:
        required: true
   
    outputs:
      build_version:
        description: "uild version"
        value: ${{ jobs.build.outputs.build_version }}    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Print build information
        run: |
          echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: Check Docker token
        run: |
          echo "Docker token is set: ${{ secrets.docker_token != '' }}"

      - name: Generate build version
        id: version
        run: |
          VERSION="v1.0-${GITHUB_SHA::7}"
          echo "Build version: $VERSION"
          echo "build_version=$VERSION" >> "$GITHUB_OUTPUT"
