name: secrets

on: 
  workflow_dispatch: 

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: read secrete and prints message
        env:
          SECRET: ${{ secrets.MY_SECRET_MESSAGE }}

        run: |
          if [ -n "$SECRET" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: directly print value
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"
