name: secrets

on: 
  push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: read secrete and prints message
        env:
          SECRETE: ${{ secrets.MY_SECRETE_MESSAGE }}

        run: |
          if [ -n "$SECRETE" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi
        
