name: smart-pipeline

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint job
        run: echo "this is lint job"


  test:
    runs-on: ubuntu-latest
    steps:
      - name: test job
        run: echo "this is test job"


  summary:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: its a push
        if: github.ref == 'refs/heads/main'
        run: echo "its a main branch"
          
      - name: Feature branch
        if: github.ref != 'refs/heads/main'
        run: echo "This is a feature branch push"  
       
      - name: commit msg
        run: echo "commit to main/feature branch"


 

         
